systemLog:
   path: /usr/local/mongodb-src/mongodb/config-2/logs/config-2.log
   destination: file
   timeStampFormat: iso8601-utc

processManagement:
   fork: true
   pidFilePath: /usr/local/mongodb-src/mongodb/config-2/pid/config-2.pid

net:
   port: 27029
   bindIp: 192.168.95.52

storage:
   dbPath: /usr/local/mongodb-src/mongodb/config-2/data
   directoryPerDB: true
   wiredTiger:
      engineConfig:
         directoryForIndexes: true

replication:
   replSetName: config
   enableMajorityReadConcern: true

sharding:
   clusterRole: configsvr